global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Java Gateway (Docker DNS name: gateway)
  - job_name: 'ledger-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway:8080']

  # Java Switch (Docker DNS name: switch)
  - job_name: 'ledger-switch'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['switch:8081']

  # Java Bank (Docker DNS name: bank)
  - job_name: 'ledger-bank'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['bank:8082']

  # Python Backend (Docker DNS name: sync-engine)
  - job_name: 'python-backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['sync-engine:8000']